FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . . 
#RUN npm run build -- --configuration production
RUN npm run build -- --configuration development

#stage 2
FROM nginx:alpine
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/sellplat /usr/share/nginx/html
#COPY ./dist/sellplat/browser/index.html /usr/share/nginx/html
EXPOSE 80
CMD [ "nginx","-g","daemon off;" ]